function layer(id,d){const e=els()[id];return`<div class="ly ${sel===id?'on':''}" data-l="${id}" data-ty="${e.type}"${e.parent?' draggable="true"':''} style="padding-left:${8+d*12}px"><span>${esc(e.name)}</span><i>${comments.some(c=>c.el===id&&!c.done)?'💬 ':''}${e.type}</i></div>`+e.children.map(c=>layer(c,d+1)).join('')}
function ptab(){const p=page();
 $('#p-pg').innerHTML=pages.map(x=>`<div class="pg"><div class="ly ${x.id===cur?'on':''}" data-pg="${x.id}"><span>${esc(x.name)}</span><i>${esc(x.slug)}</i></div>${pages.length>1?`<button data-dp="${x.id}" title="Delete page">×</button>`:''}</div>`).join('')+
 `<div class="pg"><input id="np" placeholder="New page name"><button id="ap">Add</button></div><div class="sec">Page settings</div>`+
 (isPage()?[['name','Name'],['slug','URL slug'],['title','SEO title'],['desc','SEO description'],['ogTitle','Open Graph title'],['ogDesc','Open Graph description'],['canonical','Canonical URL'],['robots','Robots']].map(([f,l])=>`<label>${l}<input data-pf="${f}" value="${esc(p[f])}"></label>`).join(''):'')}
function render(){canvas();$('#p-ly').innerHTML=(isPage()?'':'<button data-back="1" class="pri" style="width:100%;margin-bottom:6px">← Back to page</button>')+layer(page().root,0);
 $('#un').disabled=H.i<1;$('#re').disabled=H.i>=H.st.length-1;
 $('#s1').textContent=sel?`Selected: ${els()[sel].name}`:'Nothing selected';const n=checks().length;$('#s3').textContent=n?`⚠ ${n} accessibility warning${n>1?'s':''}`:'✓ No accessibility warnings';codetab()}
function insp(){const e=sel&&els()[sel],R=$('#in');
 if(!e){R.innerHTML='<p class="em">Select an element on the canvas or in Layers.</p>';return}
 const own=p=>bp==='desktop'?e.styles[p]:e.responsive[bp][p],ef=eff(e),hex=v=>/^#[0-9a-f]{6}$/i.test(v||'')?v:'#000000';
 let h=`<b>${esc(e.name)}</b> <i>${e.type}</i>`;
 if(e.parent)h+=`<div class="bt"><button data-a="up" title="Move up">↑</button><button data-a="dn" title="Move down">↓</button><button data-a="dup">Duplicate</button><button data-a="del">Delete</button><button data-a="free" class="${ef.position==='absolute'||ef.position==='fixed'?'on':''}" title="Toggle free positioning">Free</button>${e.type==='instance'||!isPage()?'':'<button data-a="comp" title="Convert to reusable component">Component</button>'}</div><label>Name<input data-n="name" value="${esc(e.name)}"></label>`;
 if(e.parent)h+=`<p class="em">${ef.position==='absolute'||ef.position==='fixed'?'Free position — drag it anywhere on the canvas.':'In flow — drag to reorder. Press Free to place it anywhere.'}</p>`;
 if(e.type==='instance'){const cc=comps.find(x=>x.id===e.comp);if(cc&&(cc.variants||[]).length)h+='<label>Variant<select data-n="variant"><option value="">Default</option>'+cc.variants.map(v=>'<option value="'+v.id+'"'+(e.variant===v.id?' selected':'')+'>'+esc(v.name)+'</option>').join('')+'</select></label>';h+='<div class="bt"><button data-ce="'+(e.variant||e.comp)+'">Edit component</button><button data-a="detach">Detach</button></div><p class="em">Instances update when the component changes. Detach to edit this copy on its own.</p>';R.innerHTML=h;return}
 if(e.text!==undefined&&!e.children.length&&e.type!=='image')h+=`<label>Text<textarea data-n="text">${esc(e.text)}</textarea></label>`;
 if(e.type==='image')h+=`<label>Image<select data-n="asset"><option value="">Placeholder</option>${assets.filter(a=>a.type==='image').map(a=>`<option value="${a.id}"${e.asset===a.id?' selected':''}>${esc(a.name)}</option>`).join('')}</select></label><label>Alt text<input data-n="alt" value="${esc(e.alt)}"></label>`;
 if(['checkbox','select','radio'].includes(e.type))h+=`<label>Label<input data-n="label" value="${esc(e.label)}"></label><label><input type="checkbox" data-n="required"${e.required?' checked':''} style="width:auto"> Required</label>`+(e.type==='select'||e.type==='radio'?`<label>Options (one per line)<textarea data-n="options" spellcheck="false">${esc(e.options)}</textarea></label>`:'');
 if(['input','textarea','file'].includes(e.type))h+=`<label>Label<input data-n="label" value="${esc(e.label)}"></label>`+(e.type!=='file'?`<label>Placeholder<input data-n="placeholder" value="${esc(e.placeholder)}"></label>`:'')+`<label><input type="checkbox" data-n="required"${e.required?' checked':''} style="width:auto"> Required</label>`+(e.type==='input'?`<label>Type<select data-n="inputType">${['text','email','password','number','tel'].map(x=>`<option${(e.inputType||'text')===x?' selected':''}>${x}</option>`).join('')}</select></label>`:'');
 if(['checkbox','select','radio','input','textarea','file'].includes(e.type))h+=`<label>Validation message<input data-n="vmsg" value="${esc(e.vmsg)}" placeholder="e.g. Please fill this in"></label>`;
 if(e.type==='form')h+=`<label>Action URL<input data-n="action" value="${esc(e.action)}" placeholder="https://your-endpoint"></label><p class="em">The form posts to any endpoint you choose. No provider is built in.</p>`;
 if(e.type==='html')h+=`<label>HTML<textarea data-n="code" spellcheck="false" style="font:11px monospace;min-height:110px">${esc(e.code)}</textarea></label><p class="em">Preview is sandboxed with scripts off. Scripts only run in your exported site.</p>`;
 if(e.type==='heading')h+=`<label>Level<select data-n="level">${[1,2,3,4,5,6].map(n=>`<option${(e.level||2)==n?' selected':''}>${n}</option>`).join('')}</select></label>`;
 h+=`<div class="bpn">Editing <b>${bp}</b> — ${bp==='desktop'?'base styles':'values with a dot are overrides; others inherit'}</div>`;
 if(['heading','paragraph','button','submit'].includes(e.type))h+=`<div class="bpn" style="font-family:${esc(ef.fontFamily||'inherit')};font-weight:${esc(ef.fontWeight||400)};font-size:14px;color:var(--tx)">Aa — The quick brown fox</div>`;
 (e.type==='image'?[...GROUPS,['Image',[['objectFit','s',['cover','contain','fill']],['objectPosition']]]]:GROUPS).filter(([t])=>t!=='Grid'||ef.display==='grid').forEach(([t,fs])=>{h+=`<div class="sec">${t}</div>`;fs.forEach(([p,ty,o])=>{const v=own(p),i=ef[p]??'';
  h+=`<div class="fl"><span class="${v!==undefined&&bp!=='desktop'?'ov':''}">${p}</span>`;
  h+=ty==='s'?`<select data-p="${p}"><option value="">${v===undefined&&i?esc(i)+' (inherited)':'—'}</option>${(typeof o==='function'?o():o).map(x=>`<option${v===x?' selected':''}>${x}</option>`).join('')}</select>`
   :ty==='c'?`<div style="display:flex;gap:4px"><input type="color" data-p="${p}" value="${hex(v??i)}"><select data-tk="${p}" title="Bind to design token"><option value="">token</option>${Object.keys(tokens).map(k=>`<option value="${k}"${v===`var(--nwx-${k})`?' selected':''}>${k}</option>`).join('')}</select></div>`
   :`<input data-p="${p}" value="${esc(v??'')}" placeholder="${esc(i)}">`;
  h+=v!==undefined?`<button class="x" data-r="${p}" title="Reset">×</button>`:'<span></span>';h+='</div>'})});
 if(e.parent){const xv=n=>{const v=efx(e)[n];return v===undefined?'':v},xown=n=>bp==='desktop'?(e[n]!==undefined&&e[n]!==''):((e.responsive[bp]||{})[n]!==undefined&&e.responsive[bp][n]!=='');
  const xrow=(n,l,ph,ty,opts)=>{const v=xv(n),own=xown(n);
   const ctl=ty==='s'?`<select data-xp="${n}"><option value="">—</option>${opts.map(x=>`<option${v===x?' selected':''}>${x}</option>`).join('')}</select>`:`<input data-xp="${n}" value="${esc(v)}" placeholder="${ph}">`;
   return`<div class="fl"><span class="${own?'ov':''}">${l}</span>${ctl}${own?`<button class="x" data-xr="${n}" title="Reset">×</button>`:'<span></span>'}</div>`};
  h+='<div class="sec">Interactions</div>'+(e.type==='button'?linkUi(e):'')+xrow('hScale','Hover scale','1.05')+xrow('hY','Hover lift px','-4')+xrow('hOpacity','Hover opacity','0.9')+xrow('hBg','Hover bg','var(--nwx-secondary)')+xrow('anim','Entrance','','s',['none','fade','slide','scale'])+xrow('dur','Duration ms','500')+xrow('delay','Delay ms','0')+'<label><input type="checkbox" data-n="reveal"'+(e.reveal?' checked':'')+' style="width:auto"> Reveal on scroll (exported site)</label><p class="em">Hover and entrance effects play in Preview. Reveal runs in the exported site.</p>'}
 if(e.parent)h+='<div class="sec">Advanced</div><label>Anchor ID<input data-n="anchorId" value="'+esc(e.anchorId)+'" placeholder="pricing"></label><label>Classes<input data-n="cls" value="'+esc(e.cls)+'" placeholder="my-class other"></label><label>Custom CSS (declarations)<textarea data-n="css" spellcheck="false" style="font:11px monospace" placeholder="backdrop-filter: blur(10px);">'+esc(e.css)+'</textarea></label><i>'+declInfo(e.css)+'</i>';
 {const cs=comments.filter(c=>c.el===sel);h+='<div class="sec">Comments'+(cs.length?' ('+cs.length+')':'')+'</div>'+cs.map(c=>`<div class="bpn" style="${c.done?'opacity:.5':''}">${esc(c.text)}<br><i>You · ${ago(c.t)}</i> <button class="x" data-cr="${c.id}" title="${c.done?'Reopen':'Resolve'}">${c.done?'↺':'✓'}</button></div>`).join('')+'<textarea id="cm" placeholder="Add a comment"></textarea><div class="bt"><button data-cp="1">Post comment</button></div>'}
 R.innerHTML=h}
function tktab(){$('#p-tk').innerHTML='<div class="sec">Colors</div>'+Object.entries(tokens).map(([k,v])=>`<div class="fl"><span>${k}</span><input type="color" data-tok="${k}" value="${v}"><span></span></div>`).join('')+'<div class="sec">Breakpoints (max-width)</div><div class="fl"><span>Tablet</span><input type="number" data-bp="tablet" value="'+bps.tablet+'"><span>px</span></div><div class="fl"><span>Mobile</span><input type="number" data-bp="mobile" value="'+bps.mobile+'"><span>px</span></div>'+'<p class="em">Bind a color property to a token in the inspector. Changing a token updates every element using it.</p>'}
function cmptab(){const off=isPage()?'':' disabled title="Not while editing a component"';
 $('#cmp').innerHTML='<div class="sec">Components</div>'+(comps.length?comps.map(c=>`<div class="pg"><button data-ci="${c.id}" style="flex:1;text-align:left"${off}>${esc(c.name)}</button><button data-ce="${c.id}">Edit</button><button data-cv="${c.id}" title="Add variant">+ Variant</button></div>`+(c.variants||[]).map(v=>`<div class="pg"><i style="flex:1;padding:4px 12px">${esc(v.name)}</i><button data-ce="${v.id}">Edit</button></div>`).join('')).join(''):'<p class="em">Select an element and press Component in the inspector to make one.</p>')}
function renderAll(){atab();if($('#gc').value!==gcss)$('#gc').value=gcss;render();insp();ptab();tktab();cmptab()}
let pageSwitchTimer=null,pageSwitchId=0;
function transitionCanvas(update){const wrap=$('#wrap'),reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 clearTimeout(pageSwitchTimer);const id=++pageSwitchId;
 if(!wrap||reduced){wrap&&wrap.classList.remove('page-leave','page-enter');update();return}
 wrap.classList.remove('page-enter');wrap.classList.add('page-leave');
 pageSwitchTimer=setTimeout(()=>{if(id!==pageSwitchId)return;update();wrap.classList.remove('page-leave');wrap.classList.add('page-enter');requestAnimationFrame(()=>requestAnimationFrame(()=>{if(id===pageSwitchId)wrap.classList.remove('page-enter')}))},110)}
function switchEditorPage(id,before){if(id===cur){if(before)before();return}transitionCanvas(()=>{if(before)before();cur=id;sel=null;renderAll()})}
function linkUi(e){const A=e.act||(e.href?'url':''),E=els(),op=(v,l)=>`<option value="${esc(v)}"${e.href===v?' selected':''}>${esc(l)}</option>`;
 let h=`<div class="fl"><span>On click</span><select data-n="act"><option value="">Nothing</option>${[['page','Go to page'],['url','Open URL'],['scroll','Scroll to section']].map(([v,l])=>`<option value="${v}"${A===v?' selected':''}>${l}</option>`).join('')}</select><span></span></div>`;
 if(A==='page')h+=`<div class="fl"><span>Page</span><select data-n="href"><option value="">Choose…</option>${pages.map(p=>op(p.slug==='/'?'index.html':p.slug.slice(1)+'.html',p.name)).join('')}</select><span></span></div>`;
 else if(A==='scroll'){const an=Object.values(E).filter(x=>x.anchorId);h+=`<div class="fl"><span>Section</span><select data-n="href"><option value="">Choose…</option>${an.map(x=>op('#'+x.anchorId,x.name)).join('')}</select><span></span></div>`+(an.length?'':'<p class="em">Give a section an Anchor ID first (Advanced).</p>')}
 else if(A==='url')h+=`<div class="fl"><span>URL</span><input data-n="href" value="${esc(e.href)}" placeholder="https://example.com"><span></span></div>`;
 return h}
function devUI(){$('#dv').innerHTML=Object.entries(DEVS).map(([k,w])=>`<button data-dev="${k}" class="${k===bp?'on':''}" title="${k} ${w}px">${k[0].toUpperCase()+k.slice(1)}</button>`).join(' ')+` <input type="number" id="vw" min="240" max="2400" value="${DEVS[bp]}" title="Viewport width (px)" style="width:62px"> px`}
function pv(on){document.body.classList.toggle('pv',on);$('#pvb').classList.toggle('on',on);$('#pvb').textContent=on?'Exit preview':'Preview';sel=on?null:sel;renderAll()}
function openShare(){const n=comments.filter(c=>!c.done).length;
 $('#shr').innerHTML=`<div><p><b>Share &amp; activity</b></p><p><i>Invites and real-time collaboration need an account service that isn't connected. This project is stored in this browser only.</i></p><div class="sec">People</div><div class="ly"><span>You</span><i>Owner</i></div><div class="sec">Comments</div><p>${n} open comment${n===1?'':'s'}. Add them from the inspector.</p><div class="sec">Activity</div>${log.length?log.slice(-30).reverse().map(l=>`<div class="ly"><span>${esc(l.what)}</span><i>${ago(l.t)}</i></div>`).join(''):'<p class="em">No activity yet.</p>'}<div class="bt"><button id="shx">Close</button></div></div>`;$('#shr').classList.add('on')}
function openKeys(){const K=[['Ctrl/Cmd + Z','Undo'],['Ctrl/Cmd + Shift + Z','Redo'],['Ctrl/Cmd + C / X / V','Copy, cut, paste element'],['Ctrl/Cmd + D','Duplicate element'],['Delete','Delete selected element'],['Ctrl/Cmd + S','Save'],['Ctrl/Cmd + P','Toggle preview'],['Esc','Deselect, exit preview or close a dialog'],['?','Show this panel']];
 $('#shr').innerHTML='<div><p><b>Keyboard shortcuts</b></p>'+K.map(([a,b])=>`<div class="ly"><span>${b}</span><i>${a}</i></div>`).join('')+'<div class="bt"><button id="shx">Close</button></div></div>';$('#shr').classList.add('on')}